apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tekton-helloworld-go
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: helloworld-go
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: __IMAGE__
