apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tekton-helloworld-go
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__
